sonar.organization=joaquinwaller
sonar.projectKey=edutrack
sonar.projectName=edutrack
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/web/src
sonar.tests=backend/src,frontend/web/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.d.ts,**/*.test.ts,**/*.test.tsx,backend/prisma/**,backend/*.js,frontend/web/public/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/web/coverage/lcov.info
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/web/tsconfig.sonar.json
