sonar.projectKey=final_class
sonar.projectName=final_class
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/web/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.d.ts,backend/prisma/**,backend/*.js,frontend/web/public/**

sonar.tests=
sonar.javascript.lcov.reportPaths=
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/web/tsconfig.sonar.json
