/**
 * Estructura técnica de tablas/columnas. Solo se necesita para generar SQL libre
 * (modo `sql`); el clasificador de intents no la usa, para ahorrar tokens.
 */
export const DATABASE_SCHEMA = `Contexto de base de datos disponible (estructura, sin datos reales):
- Tabla "User": personas/cuentas del sistema. Campos útiles: "id", "email", "username", "firstName", "lastName", "name", "nationalIdDocumentExpiresAt", "isApproved", "isActive", "lockUntil", "createdAt", "roleId". Relación con "OrgRole" por "roleId". Usá búsquedas por nombre, apellido, username o email.
- Tabla "OrgRole": rol organizacional. Campos: "id", "code", "label". Códigos esperados: ADMIN, TEACHER, STAFF, STUDENT u otros roles configurados.
- Tabla "Attendance": marcas de asistencia. Campos: "id", "userId", "eventId", "type", "status", "date", "time", "notes", "schoolYearId". "type": CHECK_IN/CHECK_OUT. "status" incluye PRESENT, LATE, ABSENT_NOT_JUSTIFIED, ABSENT_JUSTIFIED, EXIT, EARLY_EXIT, JUSTIFIED, FREE, PENDING_REVIEW, SUBSTITUTED, SUSPENDED, OUT_OF_SCHEDULE, UNIDENTIFIED_PUNCH. "date" es el día civil de la marca (medianoche Uruguay como instante UTC): filtrá día/mes/año por "date". "time" es la hora de la marca; en ausencias materializadas puede arrastrar la fecha de otra ocurrencia de la serie. "schoolYearId" permite filtrar el ciclo sin JOIN a "Event". Las ausencias existen como filas solo si un admin las materializó.
- Tabla "AttendanceIncident": incidencias derivadas de asistencia. Campos: "id", "userId", "eventId", "attendanceId", "type", "status", "title", "description", "detectedAt". "type": LATE_ARRIVAL (llegada tarde), TEACHER_NO_SHOW (falta/ausencia docente), EARLY_EXIT (salida anticipada). "status": OPEN, ACKNOWLEDGED, RESOLVED.
- Tabla "Event": clases, jornadas, reuniones y turnos. Campos: "id", "title", "type", "status", "startDate", "endDate", "startTime", "endTime", "userId", "assignedUserId", "schoolYearId", "courseOfferingId", "orientationId", "courseOrientationId", "subjectId". "status" SOLO admite: SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED, EXPIRED (NO existe 'ACTIVE' para Event). "type": JORNADA_LABORAL, REUNION, CLASE, EVENTO, CAPACITACION, CITA_MEDICA. Para eventos asignados a docentes/personal, "assignedUserId" es la persona asignada.
- Tabla "SchoolYear": ciclo lectivo (PLANNED/ACTIVE/CLOSED). Campos: "id", "code" (año entero, ej. 2026), "label", "startsOn", "endsOn", "status". Solo uno debería estar ACTIVE.
- Tabla "Course": catálogo estable de cursos. Campos: "id", "name", "code", "level" (EBI/EMS), "sortOrder", "description", "isActive". No filtra ciclo directo.
- Tabla "CourseOffering": curso ofrecido en un ciclo lectivo. Campos: "id", "courseId", "schoolYearId", "isActive", "isOffered", "visibleInFilters", "notes". Para filtros operativos por ciclo, unir "CourseOffering"."courseId" con "Course"."id" y exigir "Course"."isActive", "CourseOffering"."isActive", "CourseOffering"."isOffered" y "CourseOffering"."visibleInFilters".
- Tabla "Orientation": catálogo configurable de orientaciones/subdivisiones. Campos: "id", "name", "code", "description", "isActive", "sortOrder".
- Tabla "CourseOrientation": orientación disponible para un curso y opcionalmente para un ciclo. Campos: "id", "courseId", "orientationId", "schoolYearId", "isActive", "isOffered", "visibleInFilters".
- Tabla "Subject" (tabla real "asignaturas"): catálogo global de asignaturas/materias. Campos: "id", "name", "code", "description", "sortOrder", "isActive". Los campos "courseId" y "courseOfferingId" pueden existir solo por compatibilidad histórica.
- Tabla "SubjectCourseAssignment": asociación flexible de asignatura. Campos: "subjectId", "level", "courseId", "orientationId", "schoolYearId", "associationType" (NIVEL_COMPLETO/CURSO_COMPLETO/TRONCO_COMUN_CURSO/ORIENTACION/OPTATIVA/PERSONALIZADA), "isActive", "isOffered", "visibleInFilters".
- Tabla "StudentEnrollment": matrícula de estudiante por ciclo. Campos: "studentId", "schoolYearId", "courseOfferingId", "enrollmentStatus", "withdrawnAt". Para estudiantes por ciclo, unir "StudentEnrollment" con "Student".
- Tabla "Student": estudiante administrativo (sin cuenta de login en EduTrack). Campos: "firstName", "lastName", "documentId", "username" (usuario del aula virtual Moodle), "courseId", "contactPhone", "tutorPhone", "contactEmail" (email del alumno; la columna SQL conserva el nombre histórico), "address", "healthCardExpiresAt", "liceoAccessNotes", "enrollmentStatus" (ACTIVE/WITHDRAWN/GRADUATED/TRANSFERRED), "withdrawnAt", "withdrawalAcademicYear", "internalNotes", "createdAt".
- Tabla "StudentAttendanceSession": pase de lista de UNA ocurrencia de clase (cabecera). Campos: "id", "eventId", "eventFamilyId", "occurrenceYmd" (día civil YYYY-MM-DD), "occurrenceDate", "startAt", "endAt", "schoolYearId", "courseOfferingId", "orientationId", "courseOrientationId", "subjectId", "status" (PENDING/TAKEN), "takenByUserId", "takenAt", "rosterSize". Una clase sin fila acá es una lista que el docente todavía no pasó: NO implica que los alumnos hayan faltado.
- Tabla "StudentAttendanceEntry": marca de UN estudiante en UNA clase. Campos: "id", "sessionId", "studentId", "status" (PRESENT, LATE, ABSENT, ABSENT_JUSTIFIED), "note", "studentLastName", "studentFirstName". Para faltas de ALUMNOS unir "StudentAttendanceEntry" con "StudentAttendanceSession" (por "sessionId") y con "Student" (por "studentId"). Filtrar el período por "StudentAttendanceSession"."occurrenceYmd".
- Tabla "StudentAttendanceJustification": historial de justificaciones de faltas de alumnos. Campos: "entryId", "type", "reason", "previousStatus", "newStatus", "createdByUserId", "createdAt". El estado vigente vive en "StudentAttendanceEntry"."status", no acá.
- Tabla "StudentTuitionYear": cuota anual por estudiante. Campos: "studentId", "year", "paid", "paidAt", "amountCents", "notes". Un registro por par (studentId, year).
- Tabla "MedicalLeave": licencias o permisos. Campos: "id", "userId", "type", "status", "startDate", "endDate", "reason", "notes". No almacena certificados, diagnóstico ni datos del profesional. "status": ACTIVE/INACTIVE. El período de licencia se interpreta por solapamiento con el rango pedido.
- Tabla "BiometricPunch": marcas crudas del reloj biométrico. Campos: "id", "userId", "deviceUserId", "occurredAt", "punchType", "processStatus", "processError". "processStatus": PENDING, PROCESSED, FAILED, DUPLICATE.
- Tabla "AuditLog": auditoría del sistema. Campos: "id", "occurredAt", "action", "actorUserId", "actorIp", "source", "entityType", "entityId", "metadata".`

/**
 * Mapa de sinónimos/lenguaje natural → entidades del dominio. Es liviano y lo comparten
 * tanto el clasificador de intents como el generador de SQL: ayuda a interpretar como
 * la gente habla ("profe", "fichada", "no vino") sin arrastrar el esquema completo.
 */
export const SEMANTIC_SYNONYMS = `Mapa semántico:
- Sinónimos de personas/roles: "docente", "profesor", "profe", "maestro", "educador", "tutor" suelen mapear a usuarios con rol TEACHER; "funcionario", "personal", "staff", "administrativo", "adscripto", "bedel" suelen mapear a STAFF o personal no estudiante; "alumno", "estudiante", "chico", "gurí" suelen mapear a Student si preguntan matrícula/cursos.
- Sinónimos de eventos: "clase", "materia", "asignatura", "curso", "turno", "jornada", "reunión", "actividad" suelen mapear a Event y Course/CourseOffering/Subject según contexto.
- "eventos activos/vigentes/en curso" para Event NO es status='ACTIVE' (ese valor no existe): interpretá "vigentes/no cancelados" como "Event"."status" NOT IN ('CANCELLED','EXPIRED'), y "en curso ahora" como "status" = 'IN_PROGRESS' o el rango "startDate"/"endDate" que contiene la fecha actual.
- Sinónimos de asistencia: "marca", "marcación", "fichada", "registro", "entrada", "ingreso", "llegada", "salida", "retiro".
- "faltas", "ausencias", "no vino", "no llegó", "inasistencias": OJO, hay DOS sistemas distintos y hay que elegir según de quién se hable. Si la pregunta es sobre ALUMNOS o estudiantes (o menciona un curso, grupo o asignatura desde la óptica del alumnado), usar "StudentAttendanceEntry"."status" IN ('ABSENT', 'ABSENT_JUSTIFIED') uniendo con "Student" y "StudentAttendanceSession". Si la pregunta es sobre DOCENTES, funcionarios o personal, usar "Attendance"."status" IN ('ABSENT_NOT_JUSTIFIED', 'ABSENT_JUSTIFIED'); si habla de incidencias o ausencias docentes detectadas, también "AttendanceIncident"."type" = 'TEACHER_NO_SHOW'. Nunca mezclar las dos tablas en un mismo conteo: "Attendance" es solo del personal y "StudentAttendanceEntry" es solo de alumnos.
- "llegaron tarde", "personas que llegaron tarde", "tardanzas", "atrasos", "retrasos", "entradas tarde" en consultas directas suelen mapear a "Attendance"."type" = 'CHECK_IN' y "Attendance"."status" = 'LATE'. Si el usuario habla de incidencias, puede mapear a "AttendanceIncident"."type" = 'LATE_ARRIVAL'.
- "salidas anticipadas", "se retiró antes", "retiro temprano", "se fue antes" mapea a "Attendance"."type" = 'CHECK_OUT' y "Attendance"."status" = 'EARLY_EXIT' o a "AttendanceIncident"."type" = 'EARLY_EXIT' si pregunta por incidencias.
- "docentes con más faltas", "ranking de ausencias", "quién faltó más" requiere agrupar por usuario y contar faltas (informe de ausencias derivadas si está disponible, o incidencias TEACHER_NO_SHOW si preguntan por incidencias).
- "licencias activas/vigentes" mapea a "MedicalLeave"."status" = 'ACTIVE'.
- "usuarios pendientes", "cuentas bloqueadas", "documento por vencer" mapea a "User" con isApproved/isActive/lockUntil/nationalIdDocumentExpiresAt.`

/** Contexto completo (esquema + sinónimos) para el modo de SQL libre. */
export const DATABASE_CONTEXT = `${DATABASE_SCHEMA}

${SEMANTIC_SYNONYMS}`
