parent=keycloak.v2
import=common/keycloak

# Carga los estilos del tema base + los nuestros (los nuestros pisan al final).
styles=css/styles.css css/edutrack.css

# Mostrar el selector de "intentar otra forma" y enlaces estándar.
kcLogoIdP-google=fa fa-google
